builtins = ["flake8"]
exclude = [".venv"]
fix = true
show-fixes = true
[lint]
extend-select = ["E501", "Q000", "Q001", "Q002", "Q003"]
flake8-quotes = { inline-quotes = "double", docstring-quotes = "double"}
pep8-naming = { ignore-names = ["^_", "^__.*__$"] }
pycodestyle = { max-line-length = 79 }
mccabe = { max-complexity = 10 }